name: base
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.6.1=h59595ed_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.0=mkl
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - chardet=5.2.0=py311h38be061_2
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - conda=24.11.3=py311h38be061_0
  - conda-build=24.9.0=py311h38be061_0
  - conda-index=0.5.0=pyhd8ed1ab_0
  - conda-libmamba-solver=24.7.0=pyhd8ed1ab_0
  - conda-package-handling=2.3.0=pyh7900ff3_0
  - conda-package-streaming=0.10.0=pyhd8ed1ab_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - debugpy=1.8.17=py311hc665b79_0
  - distro=1.9.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.16.1=pyhd8ed1ab_0
  - fmt=11.0.2=h434a139_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - frozendict=2.4.6=py311h9ecbd09_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - gnutls=3.7.9=hb077bed_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblief=0.14.1=h5888daf_2
  - libmamba=1.5.10=hf72d635_1
  - libmambapy=1.5.10=py311h18a8eac_1
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.1=hb9d3cd8_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=h4ab18f5_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mamba=1.5.10=py311h3072747_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - menuinst=2.1.2=py311h38be061_1
  - mkl=2022.1.0=hc2b9512_224
  - more-itertools=10.5.0=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.3.1=hcb278e6_2
  - openssl=3.6.0=h26f9b46_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh8b19718_1
  - pkginfo=1.11.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py311h9ecbd09_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-lief=0.14.1=py311hfdbb021_2
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.10=hc5c86c4_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-libarchive-c=5.1=py311h38be061_1
  - python_abi=3.11=5_cp311
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h9ecbd09_1
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rhash=1.4.5=hb9d3cd8_0
  - ripgrep=14.1.0=h8fae777_1
  - rpds-py=0.20.0=py311h9e33e62_1
  - ruamel.yaml=0.18.6=py311h9ecbd09_1
  - ruamel.yaml.clib=0.2.8=py311h9ecbd09_1
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=hcb278e6_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - truststore=0.9.2=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - alias-free-torch==0.0.6
      - altair==5.5.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - argbind==0.3.9
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - argparse==1.4.0
      - arrow==1.4.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - audioread==3.1.0
      - auraloss==0.4.0
      - av==14.4.0
      - av-bench==1.0.0
      - babel==2.17.0
      - beartype==0.18.5
      - bitsandbytes==0.48.1
      - bleach==6.3.0
      - braceexpand==0.1.7
      - cachetools==6.2.1
      - cartopy==0.25.0
      - cfgv==3.5.0
      - clean-fid==0.1.35
      - clip==1.0
      - clip-anytorch==2.6.0
      - cloudpickle==3.1.1
      - cmake==4.1.2
      - colorlog==6.10.1
      - configparser==7.2.0
      - contourpy==1.3.2
      - coverage==7.13.0
      - cycler==0.12.1
      - cython==3.1.6
      - dctorch==0.1.2
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.18.2+02da3732
      - defusedxml==0.7.1
      - descript-audio-codec==1.0.0
      - descript-audiotools==0.7.2
      - diffusers==0.36.0
      - distlib==0.4.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - einops-exts==0.0.4
      - einx==0.3.0
      - ema-pytorch==0.2.3
      - encodec==0.1.1
      - eva-decord==0.6.1
      - expecttest==0.2.1
      - fastapi==0.120.1
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - ffmpy==0.6.4
      - fire==0.7.1
      - flash-attn==2.5.9.post1
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2024.5.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gin-config==0.5.0
      - gitdb==4.0.12
      - gitpython==3.1.0
      - google-auth==2.42.0
      - google-auth-oauthlib==0.4.6
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hypothesis==6.115.3
      - identify==2.6.15
      - imagebind==1.0.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==5.12.0
      - iniconfig==2.3.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipympl==0.9.8
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jiter==0.11.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonmerge==1.9.2
      - julius==0.2.7
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - k-diffusion==0.1.1
      - kiwisolver==1.4.9
      - kornia==0.7.3
      - kornia-rs==0.1.9
      - laion-clap==1.1.6
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning-utilities==0.15.2
      - linkify-it-py==2.0.3
      - lintrunner==0.12.5
      - lit==18.1.8
      - llvmlite==0.45.1
      - local-attention==1.8.6
      - loguru==0.7.2
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markdown2==2.5.4
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mir-eval==0.7
      - mistune==3.1.4
      - mmaudiosep==1.0.0
      - moviepy==1.0.3
      - msclap==1.3.3
      - msgpack==1.1.2
      - multidict==6.7.0
      - musdb==0.4.3
      - museval==0.4.0
      - mypy-extensions==1.1.0
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.1
      - ninja==1.11.1.1
      - nitrous-ema==0.0.1
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.5.3
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open-clip-torch==2.29.0
      - openai==2.6.1
      - opencv-python==4.9.0.80
      - optree==0.13.0
      - orjson==3.11.4
      - overrides==7.7.0
      - pandas==2.0.2
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - passt==1.0.0
      - pathtools==0.1.2
      - peft==0.17.0
      - pfzy==0.3.4
      - pillow==9.5.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - pre-commit==4.5.0
      - prefigure==0.0.9
      - proglog==0.1.12
      - progressbar==2.5
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==4.25.8
      - py-cpuinfo==9.0.0
      - pyaml==25.7.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyloudnorm==0.1.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - pyre-extensions==0.0.29
      - pyshp==3.0.3
      - pystoi==0.4.1
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - pytest-env==1.2.0
      - python-dotenv==1.2.1
      - python-etcd==0.4.5
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.1.0
      - pytorchvideo==0.1.5
      - pytube==15.0.0
      - pywavelets==1.4.1
      - randomname==0.2.1
      - regex==2025.10.23
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - rotary-embedding-torch==0.8.9
      - rsa==4.9.1
      - ruff==0.14.2
      - safehttpx==0.1.7
      - safetensors==0.4.3
      - sam-2==1.0
      - scikit-image==0.24.0
      - scikit-learn==1.7.2
      - scipy==1.11.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.43.0
      - setproctitle==1.3.7
      - setuptools==72.1.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - simplejson==3.20.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - stable-audio-tools==0.0.19
      - starlette==0.49.1
      - stempeg==0.2.6
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - tensordict==0.6.1
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.12
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomlkit==0.12.0
      - torch==2.6.0+cu124
      - torch-stoi==0.2.3
      - torchaudio==2.6.0+cu124
      - torchcodec==0.8.1
      - torchdiffeq==0.2.5
      - torchelastic==0.2.2
      - torchlibrosa==0.1.0
      - torchmetrics==0.11.4
      - torchsde==0.2.6
      - torchvision==0.21.0+cu124
      - tqdm==4.66.2
      - trampoline==0.1.2
      - transformers==4.57.1
      - triton==3.2.0
      - typer==0.20.0
      - types-dataclasses==0.6.6
      - types-regex==2025.11.3.20251106
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - uvicorn==0.38.0
      - v-diffusion-pytorch==0.0.2
      - vector-quantize-pytorch==1.14.41
      - virtualenv==20.35.4
      - wandb==0.16.6
      - webcolors==24.11.1
      - webdataset==0.2.100
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.14
      - yacs==0.1.8
      - yarl==1.22.0
      - yt-dlp==2025.10.22
prefix: /opt/conda
