_wandb:
    value:
        cli_version: 0.23.1
        e:
            m3sg7jjb90c06nepdlvsh8hyr7prbmoi:
                args:
                    - --id
                    - muddy-clip
                    - --list_train
                    - /home/prj/data/valid_muddy_mix_audios_train.csv
                    - --list_val
                    - /home/prj/data/valid_muddy_mix_audios_val.csv
                    - --img_pool
                    - maxpool
                    - --num_channels
                    - "64"
                    - --loss
                    - l1
                    - --weighted_loss
                    - "0"
                    - --num_mix
                    - "2"
                    - --log_freq
                    - "1"
                    - --arch_frame
                    - clip
                    - --num_frames
                    - "11"
                    - --stride_frames
                    - "1"
                    - --frameRate
                    - "1"
                    - --audLen
                    - "65535"
                    - --audRate
                    - "11025"
                    - --num_gpus
                    - "1"
                    - --gpu_ids
                    - "1"
                    - --workers
                    - "4"
                    - --batch_size_per_gpu
                    - "16"
                    - --lr_frame
                    - "1e-4"
                    - --lr_unet
                    - "1e-4"
                    - --num_epoch
                    - "400"
                    - --lr_steps
                    - "100"
                    - "200"
                    - "300"
                    - --dup_trainset
                    - "5"
                    - --eval_epoch
                    - "1"
                    - --ckpt
                    - /home/prj/DAVIS/result/muddy_mix_speech_sep
                    - --disp_iter
                    - "200"
                    - --num_vis
                    - "3"
                    - --wandb_run_name
                    - muddy_mix_speech_sep
                    - --wandb_mode
                    - online
                    - --dev_mode
                    - --split
                    - test
                    - --mode
                    - train
                codePath: main_fm_muddy.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "7937303777280"
                        used: "7420272713728"
                email: ccyjun123@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: b30b12c7956cf3031d85cac5c44339d8e4004525
                    remote: https://github.com/WikiChao/DAVIS.git
                gpu: NVIDIA RTX A6000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-57117fc2-3cb8-96f0-74c8-57daf4aff601
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2f0d694a-5290-be95-27e1-e745395277e9
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-d7ba7795-65cc-df9b-200e-bce3c568aa16
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-56587e25-81a2-3e2b-c8ca-0d8c965e054f
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-6f155848-6204-6ccd-68bb-5a64c9f574e7
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-0f0e9900-4760-c69c-4ad1-cb12237102af
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-5d5e763e-5a13-b9a9-b986-530bb9061ea9
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4b597b82-1b7e-e30c-7e2a-799f7955f128
                host: 880b206c63be
                memory:
                    total: "270134882304"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.35
                program: /home/prj/DAVIS/scripts/../main_fm_muddy.py
                python: CPython 3.11.10
                root: /home/prj/DAVIS/scripts
                startedAt: "2025-12-16T14:35:28.582501Z"
                writerId: m3sg7jjb90c06nepdlvsh8hyr7prbmoi
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.10
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
arch_frame:
    value: clip
audLen:
    value: 65535
audRate:
    value: 11025
batch_size:
    value: 16
batch_size_per_gpu:
    value: 16
best_err:
    value: .inf
best_sdr:
    value: -.inf
beta1:
    value: 0.9
ckpt:
    value: /home/prj/DAVIS/result/muddy_mix_speech_sep/muddy-clip-2mix-LogFreq-frames11stride1-channels64-epoch400-step100_200_300-lr_unet0.0001
dev_mode:
    value: true
device:
    value: cuda
disp_iter:
    value: 200
dup_trainset:
    value: 5
epoch_iters:
    value: 2675
eval_epoch:
    value: 1
frameRate:
    value: 1
gpu_ids:
    value: "1"
id:
    value: muddy-clip-2mix-LogFreq-frames11stride1-channels64-epoch400-step100_200_300-lr_unet0.0001
img_pool:
    value: maxpool
imgSize:
    value: 224
list_train:
    value: /home/prj/data/valid_muddy_mix_audios_train.csv
list_val:
    value: /home/prj/data/valid_muddy_mix_audios_val.csv
log_freq:
    value: 1
loss:
    value: l1
lr_frame:
    value: 0.0001
lr_steps:
    value:
        - 100
        - 200
        - 300
lr_unet:
    value: 0.0001
mode:
    value: train
num_channels:
    value: 64
num_epoch:
    value: 400
num_frames:
    value: 11
num_gpus:
    value: 1
num_mix:
    value: 2
num_sample_timesteps:
    value: 300
num_train_timesteps:
    value: 300
num_val:
    value: -1
num_vis:
    value: 3
seed:
    value: 1234
split:
    value: test
stft_frame:
    value: 1022
stft_hop:
    value: 256
stride_frames:
    value: 1
testing:
    value: false
vis:
    value: /home/prj/DAVIS/result/muddy_mix_speech_sep/muddy-clip-2mix-LogFreq-frames11stride1-channels64-epoch400-step100_200_300-lr_unet0.0001/visualization/
wandb_mode:
    value: online
wandb_project:
    value: DAVIS
wandb_run_name:
    value: muddy_mix_speech_sep
weight_decay:
    value: 0.0001
weighted_loss:
    value: 0
weights_frame:
    value: ""
weights_unet:
    value: ""
workers:
    value: 4
